-- +goose Up
ALTER TABLE merchant_book_facts
    ADD COLUMN IF NOT EXISTS tax_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cgst_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sgst_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS igst_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS tds_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hsn TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE merchant_book_facts
    DROP COLUMN IF EXISTS tax_minor,
    DROP COLUMN IF EXISTS cgst_minor,
    DROP COLUMN IF EXISTS sgst_minor,
    DROP COLUMN IF EXISTS igst_minor,
    DROP COLUMN IF EXISTS tds_minor,
    DROP COLUMN IF EXISTS hsn;
