#!/usr/bin/env bash
# Generates per-run, test-only secrets for the B12 E2E harness into the
# untracked testing/e2e/.env.harness and testing/e2e/secrets/.
# Idempotent: an existing .env.harness is kept unless --force is given.
# Works with macOS bash 3.2. Never prints secret values.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$HERE/.env.harness"
SECRETS_DIR="$HERE/secrets"
PEM="$SECRETS_DIR/ed25519_private.pem"
FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

command -v openssl >/dev/null || { echo "gen-env: openssl is required" >&2; exit 1; }

mkdir -p "$SECRETS_DIR"
if [ ! -s "$PEM" ] || [ "$FORCE" = 1 ]; then
  rm -f "$PEM"
  # PKCS#8 PEM, which edge/vault/signing.go parses with ParsePKCS8PrivateKey.
  openssl genpkey -algorithm ed25519 -out "$PEM" 2>/dev/null
  # Read by the edge container user (uid 65532) through a read-only bind mount.
  chmod 0644 "$PEM"
  echo "gen-env: wrote $PEM"
fi

if [ -s "$ENV_FILE" ] && [ "$FORCE" = 0 ]; then
  echo "gen-env: $ENV_FILE exists (use --force to regenerate)"
  exit 0
fi

b64_32() { openssl rand -base64 32 | tr -d '\n'; }
hex_n()  { openssl rand -hex "$1" | tr -d '\n'; }

umask 077
tmp="$(mktemp "$HERE/.env.harness.XXXXXX")"
cat >"$tmp" <<ENV
# Generated by testing/e2e/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# TEST-ONLY placeholders for the local harness. Untracked (see .gitignore).
# Regenerate with: testing/e2e/gen-env.sh --force
COMPOSE_PROJECT_NAME=clearline-e2e

# Postgres (single instance, one user, six databases). Hex: URL-safe.
POSTGRES_USER=clearline
POSTGRES_PASSWORD=$(hex_n 24)

# Shared HS256 JWT secret: router, edge, intents, recon.
JWT_SIGNING_SECRET=$(b64_32)
JWT_ISSUER=zord-edge
JWT_AUDIENCE=zord-console

# Shared relay lease token: relay, edge, intents, recon.
RELAY_AUTH_TOKEN=$(hex_n 32)
RELAY_OPERATOR_AUTH_TOKEN=$(hex_n 32)

# Router <-> relay.
ROUTER_AUTH_TOKEN=$(hex_n 32)

# Service JWT secret shared by vault and intents (TOK-04).
SERVICE_JWT_SIGNING_SECRET=$(b64_32)

# base64 32-byte AES keys.
ZORD_VAULT_KEY=$(b64_32)
CLEARLINE_SECRETS_KEY=$(b64_32)

# Vault (token enclave) and intents secrets.
TOKEN_SECRET=$(b64_32)
PII_TOKEN_SECRET=$(b64_32)
TOKENIZED_DATA_HASH_MASTER_SECRET=$(b64_32)
INTENT_ENGINE_INTERNAL_SERVICE_TOKEN=$(hex_n 32)

# Edge admin key.
INTERNAL_ADMIN_KEY=$(hex_n 32)

# Password Test can use for e2e signups (>= 8 chars).
E2E_USER_PASSWORD=E2e-$(hex_n 12)

# Relay dispatch: false = Mode A (default). See README before setting true.
RELAY_DISPATCH_ENABLED=false
ENV
mv "$tmp" "$ENV_FILE"
chmod 0600 "$ENV_FILE"

# Self-check: no live-key-shaped value (pattern assembled so the literal
# prefix never appears in a tracked file).
pat="$(printf '%s%s' 'rz' 'p_live_')"
if grep -q "$pat" "$ENV_FILE"; then
  echo "gen-env: generated file matches the live-key pattern; refusing" >&2
  rm -f "$ENV_FILE"
  exit 1
fi
echo "gen-env: wrote $ENV_FILE ($(grep -c '=' "$ENV_FILE") entries)"
