#!/bin/sh
# One-shot harness-setup (runs after edge, intents, recon and fake-psp are
# healthy; relay depends on it). It:
#   1. signs up tenants A and B on edge (/v1/auth/signup);
#   2. creates tenant A's razorpay connector (test mode, runtime-built
#      placeholder keys that are never written to disk);
#   3. sets the connector webhook secret and configures fake-psp with it;
#   4. writes $OUT (testing/e2e/.env.harness.runtime, gitignored) for relay
#      (sourced by its entrypoint wrapper) and for the E2E test.
# Values in $OUT are single-quoted KEY='value' lines (sh- and compose-safe).
# Secrets and tokens are never echoed to the log.
set -eu

EDGE="${EDGE_URL:-http://edge:8080}"
PSP="${FAKE_PSP_URL:-http://fake-psp:8099}"
OUT="${HARNESS_RUNTIME_FILE:-/out/.env.harness.runtime}"
PASS="${E2E_USER_PASSWORD:?E2E_USER_PASSWORD missing (gen-env.sh)}"

command -v curl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1 || apk add --no-cache -q curl jq >/dev/null

rand_hex() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }
RUN="${E2E_RUN_ID:-$(date -u +%Y%m%d%H%M%S)-$(rand_hex 3)}"

# call METHOD URL BODY [BEARER]: prints the body, fails on non-2xx.
call() {
  _m="$1"; _u="$2"; _b="$3"; _t="${4:-}"
  _resp="$(mktemp)"
  if [ -n "$_t" ]; then
    _code="$(curl -sS -o "$_resp" -w '%{http_code}' -X "$_m" "$_u" -H 'Content-Type: application/json' -H "Authorization: Bearer $_t" --data "$_b")"
  else
    _code="$(curl -sS -o "$_resp" -w '%{http_code}' -X "$_m" "$_u" -H 'Content-Type: application/json' --data "$_b")"
  fi
  case "$_code" in
    2??) cat "$_resp"; rm -f "$_resp" ;;
    *) echo "harness-setup: $_m $_u -> HTTP $_code" >&2
       # Error bodies may echo request fields; print keys only.
       jq -c 'if type=="object" then (keys) else . end' "$_resp" >&2 2>/dev/null || true
       rm -f "$_resp"; return 1 ;;
  esac
}

# pick JSON 'jq-alternatives': first non-null match.
pick() { jq -r "$1 // empty" | head -n1; }

signup() { # $1 = A|B
  _lc="$(echo "$1" | tr 'A-Z' 'a-z')"
  _name="e2e-$1-$RUN"
  _email="$_lc+$RUN@example.test"
  _body="$(jq -nc --arg t "$_name" --arg n "E2E $1" --arg e "$_email" --arg p "$PASS" \
    '{tenant_name:$t,name:$n,email:$e,password:$p}')"
  _r="$(call POST "$EDGE/v1/auth/signup" "$_body")"
  _jwt="$(echo "$_r" | pick '.access_token, .data.access_token, .token, .tokens.access_token')"
  _tid="$(echo "$_r" | pick '.tenant_id, .tenant.id, .tenant.tenant_id, .data.tenant_id, .user.tenant_id')"
  if [ -z "$_jwt" ] || [ -z "$_tid" ]; then
    echo "harness-setup: signup $1 response missing access_token/tenant_id; keys: $(echo "$_r" | jq -c 'paths|map(tostring)|join(".")' | tr '\n' ' ')" >&2
    return 1
  fi
  eval "T_$1_NAME=\$_name; T_$1_EMAIL=\$_email; T_$1_JWT=\$_jwt; T_$1_ID=\$_tid"
  echo "harness-setup: tenant $1 signed up (tenant_id=$_tid)"
}

signup A
signup B

# Placeholder test-mode keys, built at runtime; never persisted or logged.
KEY_PREFIX="$(printf '%s%s' 'rz' 'p_test_')"
KEY_ID="${KEY_PREFIX}e2e$(rand_hex 7)"
KEY_SECRET="e2e$(rand_hex 12)"
CONN_RESP="$(call POST "$EDGE/v1/connectors/razorpay" \
  "$(jq -nc --arg k "$KEY_ID" --arg s "$KEY_SECRET" '{mode:"test",key_id:$k,key_secret:$s}')" "$T_A_JWT")"
unset KEY_ID KEY_SECRET
CONNECTOR_ID="$(echo "$CONN_RESP" | pick '.connector_id, .id, .connector.id, .connector.connector_id, .data.connector_id')"
[ -n "$CONNECTOR_ID" ] || { echo "harness-setup: connector response has no connector_id" >&2; exit 1; }
echo "harness-setup: connector created (connector_id=$CONNECTOR_ID)"

WEBHOOK_SECRET="${E2E_WEBHOOK_SECRET:-whsec_e2e_$(rand_hex 20)}"
call PUT "$EDGE/v1/connectors/$CONNECTOR_ID/webhook-secret" \
  "$(jq -nc --arg w "$WEBHOOK_SECRET" '{webhook_secret:$w}')" "$T_A_JWT" >/dev/null
echo "harness-setup: webhook secret set on connector"

call POST "$PSP/_admin/config" \
  "$(jq -nc --arg c "$CONNECTOR_ID" --arg w "$WEBHOOK_SECRET" '{connector_id:$c,webhook_secret:$w}')" >/dev/null
echo "harness-setup: fake-psp configured"

# Relay connector map. TO VERIFY against backend/relay/cmd/main.go:193
# (format of RELAY_DISPATCH_CONNECTOR_UUID_MAP): default is a JSON object
# {"<key>":"<connector uuid>"}; set HARNESS_CONNECTOR_MAP_FORMAT=kv for
# "key=uuid". The key defaults to tenant A's slug (tenant_name).
MAP_KEY="${HARNESS_CONNECTOR_MAP_KEY:-$T_A_NAME}"
case "${HARNESS_CONNECTOR_MAP_FORMAT:-json}" in
  kv) CONN_MAP="$MAP_KEY=$CONNECTOR_ID" ;;
  *)  CONN_MAP="$(jq -nc --arg k "$MAP_KEY" --arg v "$CONNECTOR_ID" '{($k):$v}')" ;;
esac

q() { printf "%s='%s'\n" "$1" "$(printf '%s' "$2" | sed "s/'/'\\\\''/g")"; }
tmp="$OUT.tmp.$$"
umask 077
{
  echo "# Generated by harness-setup at $(date -u +%Y-%m-%dT%H:%M:%SZ). TEST-ONLY. Untracked."
  q E2E_RUN_ID "$RUN"
  q E2E_TENANT_A_ID "$T_A_ID"
  q E2E_TENANT_A_NAME "$T_A_NAME"
  q E2E_TENANT_A_EMAIL "$T_A_EMAIL"
  q E2E_TENANT_A_JWT "$T_A_JWT"
  q E2E_TENANT_B_ID "$T_B_ID"
  q E2E_TENANT_B_NAME "$T_B_NAME"
  q E2E_TENANT_B_EMAIL "$T_B_EMAIL"
  q E2E_TENANT_B_JWT "$T_B_JWT"
  q E2E_CONNECTOR_ID "$CONNECTOR_ID"
  q E2E_WEBHOOK_SECRET "$WEBHOOK_SECRET"
  q RELAY_DISPATCH_CONNECTOR_UUID_MAP "$CONN_MAP"
} >"$tmp"
# Never write a live-key-shaped value.
if grep -qE "$(printf '%s%s' 'rz' 'p_live_')" "$tmp"; then
  rm -f "$tmp"; echo "harness-setup: live-key pattern in output; refusing" >&2; exit 1
fi
chmod 0644 "$tmp"   # relay runs as uid 65532 and must read it
mv "$tmp" "$OUT"
echo "harness-setup: wrote $(basename "$OUT") (run $RUN)"
